name: ${project.name}
version: ${project.version}
main: com.slender.Main
authors: [ Slender ]
description: test
commands:
  dreload:
    description: Eklentiyi Yeniler
    aliases:
      - screload
    usage: /<command>
  yetkilisohbet:
    description: Yetkili Sohbet Komutu
    aliases:
      - sc
      - staffchat
    usage: /<command>

